resources:

- name: git-repo
  type: git
  source:
    branch: master
    uri: git@github.com:SapInnovation/kafka-setup.git
    

jobs:

- name: run-kafka-setup
  plan:
    - get: git-repo
    - task: run-setup
      config:
          inputs:
          - name: git-repo
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: {repository: ubuntu}
          run:
            path: ./ci/kafka_remote_setup.sh
            args:
            - ((auth-data.DESTINATION_SERVER_USER))
            - ((auth-data.DESTINATION_SERVER_PASSWORD))
            - ((auth-data.DESTINATION_SERVER))
